-- ═══════════════════════════════════════════════════════════════════════════
-- better-auth tables
--
-- ⚠️  THESE TABLES ARE NOT OURS. better-auth owns their shape, and the
-- definitions below were generated from `getAuthTables()` in better-auth 1.7.1
-- rather than written from memory. If better-auth is upgraded, re-derive them
-- and diff — do not assume they are stable across versions.
--
-- WHY THEY EXIST AT ALL: better-auth is the single sanctioned exception to
-- strict ports-and-adapters (docs/codebase-structure.md §7). Wrapping a library
-- that owns its own schema and middleware means fighting it continuously, so
-- instead its REACH is bounded: only src/modules/identity/adapters/better-auth/
-- and src/http/middleware/auth.ts may import it, enforced by dependency-cruiser.
-- Everything else in sebp sees a branded UserId and nothing more.
--
-- THE BOUNDARY WITH OUR SCHEMA:
--   better-auth owns  →  user, session, account, verification
--   we own            →  otp_challenges (0000), and every future table
--
-- technical-design.md §4.1 sketches a `users` table. It does NOT survive contact
-- with these — `user` below is the real one. Domain concepts that are not
-- authentication (Startup, roles, permissions) stay ours, live in
-- modules/identity/domain, and are keyed by user.id.
--
-- NOTE ON CONVENTIONS: these tables do NOT follow sebp's own schema conventions
-- (no `version`, no `deleted_at`, singular table names, camelCase columns). That
-- is a consequence of the exception, not an oversight. Our tables follow our
-- conventions; these follow better-auth's.
--
-- NOTE ON `verification`: better-auth uses it for its own flows. sebp does NOT
-- use it — OTP lives in our `otp_challenges` table (0000) so that delivery goes
-- through the Notifier port. The table is created because better-auth expects it
-- to exist, and it should remain empty in normal operation.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE `user` (
	-- Supplied by us (UUIDv7 via the IdGenerator port), not generated by
	-- better-auth — `advanced.database.generateId: false` in the instance config,
	-- so every table in sebp shares one id strategy.
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL UNIQUE,
	-- Always true in sebp: an account cannot exist until an OTP has proven the
	-- address, so there is no unverified state to represent.
	`emailVerified` integer NOT NULL DEFAULT 0,
	`image` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint

CREATE TABLE `session` (
	`id` text PRIMARY KEY NOT NULL,
	`expiresAt` integer NOT NULL,
	-- The opaque value held in the session cookie. Server-side sessions are used
	-- rather than JWTs specifically so staff access can be revoked immediately.
	`token` text NOT NULL UNIQUE,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	`ipAddress` text,
	`userAgent` text,
	`userId` text NOT NULL REFERENCES `user`(`id`) ON DELETE CASCADE
);
--> statement-breakpoint
CREATE INDEX `idx_session_user` ON `session` (`userId`);
--> statement-breakpoint
CREATE INDEX `idx_session_token` ON `session` (`token`);
--> statement-breakpoint

CREATE TABLE `account` (
	`id` text PRIMARY KEY NOT NULL,
	`issuer` text NOT NULL,
	`accountId` text NOT NULL,
	-- 'credential' for email+password. OAuth providers would appear here if ever
	-- added; sebp has none today.
	`providerId` text NOT NULL,
	`userId` text NOT NULL REFERENCES `user`(`id`) ON DELETE CASCADE,
	`accessToken` text,
	`refreshToken` text,
	`idToken` text,
	`accessTokenExpiresAt` integer,
	`refreshTokenExpiresAt` integer,
	`scope` text,
	-- scrypt hash as `salt:key` hex, 161 characters (verified in TASK-39).
	-- N=16384, r=16, p=1 — NOT bcrypt, which is unavailable on Workers.
	`password` text,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_account_user` ON `account` (`userId`);
--> statement-breakpoint

CREATE TABLE `verification` (
	`id` text PRIMARY KEY NOT NULL,
	`identifier` text NOT NULL,
	`value` text NOT NULL,
	`expiresAt` integer NOT NULL,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_verification_identifier` ON `verification` (`identifier`);
